[package]
name = "tdb"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29", features = ["ptrace", "process", "signal", "personality"] }
libc = "0.2"
goblin = "0.8"
rustyline = "14"
anyhow = "1"
gimli = "0.34.0"
iced-x86 = "1.21.0"
signal-hook = "0.4.4"
rust-i18n = "4"
cfgrammar = "0.15"
lrlex = "0.15"
lrpar = "0.15"

[build-dependencies]
cfgrammar = "0.15"
lrlex = "0.15"
lrpar = "0.15"
